language: python
sudo: required
before_install:
  - sudo apt-get install gfortran mpich libnetcdf-dev netcdf-bin
python:
  - '2.7'
  - '3.6'
script:
  - cd src; make SETUP_ARGS="gfortran $(dirname $(dirname $(which nc-config)))"
  - make USE_NETCDF=TRUE
branches:
  only:
  - master
