dist: trusty
language: python
sudo: required

addons:
   apt:
      packages:
         - netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran

python:
  - '2.7'
  - '3.6'

script:
  - cd bld; ./cvmix_setup gfortran $(dirname $(dirname $(which nc-config)))
  - cd ../CVMix_tools; ./run_test_suite.sh --already-ran-setup
  - cd ../reg_tests/Bryan-Lewis/; ./Bryan-Lewis-test.sh --cmake

branches:
  only:
  - master
