#!/usr/bin/env python

# Allow tab completion
try:
  import readline,glob
except ImportError:
  print "Can not find readline or glob package, so tab-complete will not work"
else:
  def complete(text, state):
    return(glob.glob(text+'*')+[None])[state]
  readline.set_completer_delims(' \t\n;')
  if 'libedit' in readline.__doc__:
    readline.parse_and_bind("bind ^I rl_complete")
  else:
    readline.parse_and_bind("tab: complete")
  readline.set_completer(complete)

# Print standard information about this tool
print "This utility needs to be run before the included Makefile will"
print "successfully compile CVMix. It collects information about your compiler"
print "and associated libraries, and saves it in the .CVMix_env file. Note that"
print "it only needs to be run once, though you should run it again if anything"
print "changes.\n"

# For now, just need fortran compiler and netCDF location / flags
compiler = raw_input('Fortran compiler (mpi not necessary): ')
netcdf_dir = raw_input('Directory containing netcdf (enter "need_both" to enter netcdf include directory and netcdf lib directory separately): ')
if netcdf_dir == "need_both":
  netcdf_inc = raw_input('netCDF/include location: ')
  netcdf_lib = raw_input('netCDF/include location: ')
else:
  netcdf_inc = netcdf_dir+"/include"
  netcdf_lib = netcdf_dir+"/lib"

fid = open(".CVMix_env", 'w')
fid.write("FC = " + compiler+"\n")
fid.write("NETCDF_INC = " + netcdf_inc+"\n")
fid.write("NETCDF_LIB = " + netcdf_lib+"\n")
